name: Release

on:
  push:
    branches:
    - main
    - master
    paths:
    - '.changeset/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
        registry-url: 'https://registry.npmjs.org/'

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Project
      run: pnpm build

    - name: Create .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Check for Changesets
      id: check_changesets
      run: |
        if [ -z "$(ls -A .changeset 2>/dev/null)" ]; then
          echo "No changesets found. Skipping release."
          exit 0
        fi

    - name: Auto Version & Publish
      if: success()
      run: |
        pnpm version patch --no-git-tag-version
        pnpm publish --access public
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Clean Up Changesets
      if: success()
      run: |
        rm -rf .changeset
        git add .
        git commit -m "chore: remove processed changesets" || echo "No changesets to clean"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
